# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0005_auto_20170130_0213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='url',
            new_name='slug',
        ),
    ]
