# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0006_auto_20170130_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(max_length=20),
        ),
    ]
