# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0011_auto_20170211_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_group',
            field=models.CharField(choices=[('FL', 'Follower'), ('WR', 'Writer'), ('AD', 'Admin')], default='FL', max_length=2),
        ),
    ]
